-- En este archivo deben estar tus ejercicios de consultas sql

SELECT NOMBRES FROM EMPLEADOS ORDER BY NOMBRES DESC;
SELECT e.NOMBRES, p.PUESTO, l.LOCALIDAD FROM EMPLEADOS e JOIN PUESTOS p ON e.PUESTO_ID = p.ID JOIN DEPARTAMENTO d ON e.DEPARTAMENTO_ID = d.ID JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID WHERE p.PUESTO = 'Soporte';
SELECT NOMBRES FROM EMPLEADOS WHERE NOMBRES LIKE '%o';
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD FROM EMPLEADOS e JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID WHERE l.LOCALIDAD = 'Carlos Paz';
SELECT e.NOMBRES, e.SUELDO, l.LOCALIDAD FROM EMPLEADOS e JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID WHERE e.SUELDO BETWEEN 10000 AND 13000;
SELECT d.DENOMINACION AS DEPARTAMENTO, COUNT(e.ID) AS NUMERO_EMPLEADOS FROM DEPARTAMENTOS d JOIN EMPLEADOS e ON d.ID = e.DEPARTAMENTO_ID GROUP BY d.ID HAVING COUNT(e.ID) > 5;
SELECT e.NOMBRES FROM EMPLEADOS e JOIN DEPARTAMENTOS d ON e.DEPARTAMENTO_ID = d.ID JOIN LOCALIDADES l ON d.LOCALIDAD_ID = l.ID JOIN PUESTOS p ON e.PUESTO_ID = p.ID WHERE l.LOCALIDAD = 'Córdoba' AND (p.PUESTO = 'Analista' OR p.PUESTO = 'Programador');
SELECT AVG(SUELDO) AS SUELDO_MEDIO FROM EMPLEADOS;
SELECT MAX(SUELDO) AS MAXIMO_SUELDO FROM EMPLEADOS WHERE DEPARTAMENTO_ID = 10;
SELECT MIN(e.SUELDO) AS SUELDO_MINIMO FROM PUESTOS p ON e.PUESTO_ID = p.ID WHERE p.PUESTO = 'Soporte';
SELECT p.PUESTO, SUM(e.SUELDO) AS SUMA_SUELDOS FROM EMPLEADOS e JOIN PUESTO p ON e.PUESTO_ID = p.ID GROUP BY p.PUESTO;
